name: Use Metadata Injection Action

on:
  push:
    branches:
      - main
      - master
      - wip

permissions:
    contents: write

jobs:
  inject-metadata:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Inject metadata using the custom action
        id: inject
        uses: yaouDev/inject-metadata@wip
        with:
          source_code_path: 'src'
          debug_mode: 'yes'

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Updated Git commit metadata"